### ISSUE TITLE
The editor theme is glitched

### ISSUE THREAD

**Issue by HazelNutHoney** [joshdavies14/intellij-fp-theme#70]
This showed in 1.2.5 and is still a issue in 1.2.6 but it is showing the ide's editor as light theme but the rest is still purple
![image](https://github.com/joshdavies14/intellij-fp-theme/assets/87324700/f131e9d0-df3f-4d71-a673-e1c5bae3ae33) as you can see the tabs like gradle and the project structure are purple its just the middle part that's stuck in light for some reason
![image](https://github.com/joshdavies14/intellij-fp-theme/assets/87324700/67459cb5-64e2-4cf5-a103-88e5073d1d62)

**Comment by joshdavies14** [comment]
Hi @HazelNutHoney - I've just updated to v1.2.6 in my local copy of the IDE and it loads correctly for me. I did have to go into my theme settings and manually select the editor scheme to be "fp-theme" if that helps at all? It was originally incorrectly set to "Dark". Let me know if that doesn't fix it and I can try taking a deeper look, but with writing my dissertation at the moment this isn't a major priority...

**Comment by SirValecekLuis** [comment]
Hi, I second to this unfortunately, the IDE does not show any error but is broken in the same way as my last issue reported.

**Comment by joshdavies14** [comment]
@SirValecekLuis Have you tried ensuring the editor scheme is actually enabled in the Appearance Settings, as mentioned in my comment above?

<img width="1094" alt="Screenshot 2024-04-03 at 13 42 19" src="https://github.com/joshdavies14/intellij-fp-theme/assets/30526591/53972917-ee2e-4833-b3b1-41a18f39fda3">

**Comment by SirValecekLuis** [comment]
I have even reinstalled the whole theme without any success. (As you can see, there are remains of the last used theme.)

![image](https://github.com/joshdavies14/intellij-fp-theme/assets/75647322/e9fdfbc0-a9cc-4330-9e5e-b129f63fac3f)

**Comment by joshdavies14** [comment]
@SirValecekLuis what version of CLion are you using, please? I see you don't have the "editor scheme" option that I do. I've fresh installed the theme (tbh I don't use it myself now so I didn't have it installed in any IDE) and it worked first time for me. I'm using the 2024.1 Release Candidate.

**Comment by SirValecekLuis** [comment]
![image](https://github.com/joshdavies14/intellij-fp-theme/assets/75647322/bc5de56f-9eb8-40f0-8985-81b20fee0338)

**Comment by joshdavies14** [comment]
Thanks - I think the setting is in a diffeent place in older versions of the IDE.

Please can you go to Settings -> Editor -> Colour Scheme and verify that fp-theme is set there? If it doesn't show in the list I had to restart my IDE after installing it for it to appear.

I don't know why it doesn't set automatically so I'll look into it when I have some free time, but ensuring that value is set, the theme loads correctly in your version of CLion for me.

**Comment by SirValecekLuis** [comment]
Thank you, fixed. 

![image](https://github.com/joshdavies14/intellij-fp-theme/assets/75647322/a8183d5a-13ff-4141-b228-c7e11c93ba1d)

**Comment by HazelNutHoney** [comment]
@joshdavies14 Sorry I just noticed this lol but manually changing it worked! Thx so much

**Comment by joshdavies14** [comment]
@HazelNutHoney no worries at all, thanks for confirming! And @SirValecekLuis also thanks for confirming!

I've created #71 to remind myself to look at why this sometimes doesn't auto apply, job for myself for sometime in the future. I'll close this issue now we at least have some sort of a solution! :)
